import os
from pathlib import Path

APP_TITLE = "Qdrant PDF RAG Demo"
UPLOAD_DIR = Path("uploads")
DEFAULT_CHUNK_SIZE = 1000
DEFAULT_CHUNK_OVERLAP = 200
DEFAULT_TOP_K = 10
DEFAULT_CONTEXT_MAX_CHUNKS = 5
DEFAULT_CONTEXT_MIN_SCORE = 0.0
EMBEDDING_MODEL_NAME = "BAAI/bge-small-en-v1.5"
EMBEDDING_QUERY_PREFIX = "query: "
EMBEDDING_PASSAGE_PREFIX = "passage: "
EMBEDDING_NORMALIZE = True
RERANK_ENABLED_DEFAULT = True
RERANKER_MODEL_NAME = "cross-encoder/ms-marco-MiniLM-L-6-v2"
VECTOR_SIZE = 384  # all-MiniLM-L6-v2 output dimension
QDRANT_URL = os.getenv("QDRANT_URL", "")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY", "")
QDRANT_COLLECTION = os.getenv("QDRANT_COLLECTION", "pdf_demo_chunks_bge_small_v1")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "openai/gpt-4o-mini")
OPENROUTER_BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1/chat/completions")
OPENROUTER_HTTP_REFERER = os.getenv("OPENROUTER_HTTP_REFERER", "")
OPENROUTER_APP_TITLE = os.getenv("OPENROUTER_APP_TITLE", APP_TITLE)
CONTEXT_MAX_CHUNKS = int(os.getenv("CONTEXT_MAX_CHUNKS", str(DEFAULT_CONTEXT_MAX_CHUNKS)))
CONTEXT_MIN_SCORE = float(os.getenv("CONTEXT_MIN_SCORE", str(DEFAULT_CONTEXT_MIN_SCORE)))
